feat: add volumes and printable observation
vtex/invoicer-mock pull request #14
Opened 2020-10-23 13:01 UTC by rodrigoimenes

Adding Volumes and Printable Observation to the mock, just to keep it updated.

2020-10-23 16:17 UTC, gtkatakura requested changes

2020-10-23 16:17 UTC, gtkatakura commented on node/resources/Invoice.ts
> +    this.volumes = notification.volumes || [{ index: 0 }]
aqui precisa fazer um `map` transformando para usar `new Volume`, se nao usa a classe atoa

se nao, melhor ser so `type` mesmo para n enganar, parecendo que usa `new Volume` em algum lugar, mas n usa

eu acho que mudar para `type` eh melhor aqui

2020-10-23 16:17 UTC, gtkatakura commented on node/resources/Notification.ts
> +    this.volumes = params.volumes || [{ index: 0 }]
aqui tbm, ou trocar `Volume` para `type` ou fazer o `map + new Volume`

2020-10-26 14:51 UTC, guilhermebruzzi approved these changes

2020-11-03 12:11 UTC, IvanIFJ approved these changes

2020-11-03 12:32 UTC, merged